### ISSUE TITLE
Publish this extension on Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by StrangePeanut** [iorate/ublacklist#108]
The number of Edge users is growing rapidly. I would love to see uBlacklist being made available on Microsoft Edge Add-ons.

**Comment by iorate** [comment]
It is of low priority because
- Edge users can install this extension from Chrome Web Store
- It takes time and effort to update this extension in Microsoft Edge Add-ons because they do not offer publishing APIs unlike Chrome Web Store and Firefox Add-ons

If someone can do it for me, of course I welcome it.

**Comment by mtgq** [comment]
> The number of Edge users is growing rapidly. I would love to see uBlacklist being made available on Microsoft Edge Add-ons.



> The number of Edge users is growing rapidly. I would love to see uBlacklist being made available on Microsoft Edge Add-ons.

When can it be released? like edge

**Comment by Remonli** [comment]
Any news for Edge Addon store ?
