### ISSUE TITLE
Hide after load for better user experience

### ISSUE THREAD

**Issue by icetbr** [iorate/uBlacklist#154]
Hi, the script prevent search results from loading until it analyses all links. Since I have big list of sites, and 95% of the time it doesn't find a single match, it would be nicer to have the links disappear instead after loading the results instead.

It takes about 2s for my search results to appear with the extension on, and it's instant when I turn it off.

Thanks.

**Comment by iorate** [comment]
This suggestion is unacceptable. If we filter search results after they are loaded, results that should be hidden will appear for a moment, which is exteremely unpleasant for me. It is one of the reasons why I created this extension instead of 'Personal Blocklist (by Google)'.

> It takes about 2s for my search results to appear with the extension on, and it's instant when I turn it off.

This is another problem. I think we can improve performance for big lists by *compiling* them just like uBlock Origin does.
