### ISSUE TITLE
Consider uBlocklist?

### ISSUE THREAD

**Issue by NorthIsUp** [iorate/ublacklist#160]
"blacklist" is a term that has negative racial connotation in America, it would be cool to consider a different name.

**Comment by riley-hivot** [comment]
??? does it? I don't think it does my guy.

**Comment by megakraken** [comment]
take your politics elsewhere

**Comment by DetachHead** [comment]
why does the word black remind you of slavery?

**Comment by iorate** [comment]
Honestly, I don't want to touch this controversial issue. 

I won't rename this extension as I am attached to the current name.

Anyone who is dissatisfied can freely fork this extension, rename it to an "inclusive" name, and publish it.

**Comment by masterofobzene** [comment]
> "blacklist" is a term that has negative racial connotation in America, it would be cool to consider a different name.

Another kid with the wrong idea of revolution or cause. 
See, the problem of ratial discrimination in your country is not going to be solved by changing words or censoring. It's going to be solved the day new generations just stop thinking black people are "vulnerable" or in "disadvantage"  because they dark skinned and "they have to protect them". Its going to be solved the day that old generations (the ones that are discriminating) just pass away. Sorry to be so direct, but its the truth. Nobody will be able to convince those old generations that black skin is just that, black skin.
This means that you should help people in real trouble and visibilize real injustice, but going as far as censoring stuff like this, is just stupid and useless.

**Comment by KotlinIsland** [comment]
![image](https://user-images.githubusercontent.com/65446343/152290070-2f2caf7f-4feb-419a-9e12-818fda234153.png)

# 😳😳😳😳😳😳😳
