### ISSUE TITLE
Add Yandex support

### ISSUE THREAD

**Issue by ibrahimBeladi** [iorate/uBlacklist#162]
Add Yandex support

**Comment by Semro** [comment]
Duplicate of https://github.com/iorate/uBlacklist/issues/91

**Comment by iorate** [comment]
As @Semro pointed out, your issue is a duplicate of #91, which was closed because nobody contributed to it. I didn't (and don't) have the time or motivation to do it either.

Do you plan to contribute to this issue? If so, please implement the Yandex support yourself and create a pull request. See also #63.
