### ISSUE TITLE
插件不能屏蔽网页快照和精选答案。

### ISSUE THREAD

**Issue by LItingLove** [iorate/ublacklist#185]
## Actual Behavior
Chrome搜索任意字段后，在搜索栏不能屏蔽网页快照相关链接。

## Specifications

- OS:Windows10 19043.1415
- Browser:Chrome 97.0.4692.71
- Other extensions that might interfere:
附录相关截图：https://sm.ms/image/eVKn4vbYWrkfMjT
https://sm.ms/image/AxtgFndVXSezsT6
https://sm.ms/image/NTuKgFbvXn86CZH
https://sm.ms/image/qgP4NEvmVkXA5ex

**Comment by iorate** [comment]
It should be addressed in v7.2.2.

It seems that Google has started to roll out a new DOM structure of search results for some users. Probably it is the case with this issue and #186.
This problem is not reproduced in my main Google account either. To reproduce this kind of problem, we need to repeatedly clear cookies and reload until getting the new structure. There are some extensions to easily do it (e.g. [Clear Cookie and Reload](https://chrome.google.com/webstore/detail/clear-cookie-and-reload/clinijjpaohndgmfepgpifcfnmlecbom?hl=en-US)).
