### ISSUE TITLE
Include all search engines in manifest

### ISSUE THREAD

**Issue by vincentbernat** [iorate/ublacklist#189]
Hey!

Currently, using the extension with a search engine other than Google requires to allow the extension full access to all visited websites. It would be nice if we didn't have to. Two arguments for that:

1. Only the Google list is quite long. The list for the other search engines is far shorter. If there is no hard limit, this should not be a hassle to add them.
2. Manifest V3 and Safari extension are already including the whole list. See https://github.com/iorate/ublacklist/commit/78a85b780bc276da673361d3b929ae5cea9e3486#diff-28cc1860c9d64e7be53526567b22f43facdd67095137b5d6de8295582f304abaR33.

**Comment by HoneyLuka** [comment]
On Safari, if you choose to 'Always allow on every website', the extension can only access all the sites defined in the manifest file.  (If I'm not mistaken). So recommended user choose to 'Always allow on every website', just for the convenience of the user.

If you choose to allow specific sites, I think the extension will still work fine.

**Comment by iorate** [comment]
> Currently, using the extension with a search engine other than Google requires to allow the extension full access to all visited websites.

That is not the case. When you use this extension with a search engine other than Google, this extension requires access to the search engine result pages only.
What you mean may be that the optional permissions declared in manifest.json are `*://*/*`. This extension never requires the "universal set" of `*://*/*`. Only "subsets" necessary for search engine filtering, sync, or subscription are required.

By the way, I don't have a plan to update the host permissions in the near future. If I add new permissions, the extensions already installed will *stop* to require the users to grant the permissions. It will be annoying for most of the existing users.

I may update the permissions on introducing manifest v3 (MV3). However, because MV3 does not support optional host permissions yet (to be more precise, Chrome has not yet changed host permissions to be optional by default [[1](https://developer.chrome.com/docs/extensions/mv3/intro/platform-vision/#future-related-changes)] [[2](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/u5tRDEn8yjU/m/PZn4o4ZlAgAJ)]), I cannot introduce MV3 right now. When the time limit (Jan 2023, when MV2 extensions stop) approaches, I may be forced to make some decisions.

**Comment by vincentbernat** [comment]
Thanks, you are right.
