### ISSUE TITLE
Export/import all settings

### ISSUE THREAD

**Issue by chrisgrieser** [iorate/ublacklist#216]
I use neither Google Drive nor Dropbox, so having an option to export all settings would be very useful to move settings to a different browser or machine.

Right now, the extension can only export/import blocked sites, but not the rest (appearance, subscriptions, etc.)

**Comment by rasqual** [comment]
When pushing the extension in Chrome policy (thinking students here), the small black/whitelist ability is OK -- but it would be better still to be able to push subscriptions and other key settings. 

This is in part concerned with CIPA compliance (denying students looking for things they shouldn't find), but it's also just darned handy to filter bogus searches from students who are looking for legitimate stuff. 

Schools use more robust tools for CIPA compliance, so the subscription thing to help students not be presented with crap in their legit work would be the big benefit. 

I'm piggybacking this because a great way to come up with a JSON for pushing Chrome policy would be an export of a well-configured set of settings. The same JSON could be used for export/import/policy.

**Comment by nicoleahmed** [comment]
i would love this function too! or the ability to copy all subscriptions easily without having to click into each subscription individually to see what the url is 

brill work thank you iorate!
