### ISSUE TITLE
Settings for "Other search engines" and "Items to Sync" are not synchronized.

### ISSUE THREAD

**Issue by Ry-315** [iorate/ublacklist#265]
## Expected Behavior
"Other Search Engines" and "Items to Sync" settings are also synced to the cloud.
## Actual Behavior
Those settings will not be synchronized.
## Steps to Reproduce the Problem

1.Turn on sync to Google Drive or Dropbox to sync settings with other devices.
2.Add "General Settings" to "Items to Sync" and enable the "Other Search Engines" setting.
3.The other device does not reflect that.

## Specifications

- OS:Windows11, macOS Monterey 12.5.1
- Browser:Microsoft Edge (Would Google Chrome not have this problem?)
- Other extensions that might interfere:AdGuard

*Note: Some machine translation is used.

**Comment by iorate** [comment]
Intended behavior; Enabling support for other search engines always requires a user gesture such as a button click because `chrome.permissions.request` cannot be called without a user gesture. Therefore, background synchronization cannot enable support for other search engines.

Indeed, it is a bit strange that all settings in the `General` section are not synchronized when the `General` switch is turned on, but I don't think it is a serious problem.

**Comment by Ry-315** [comment]
What about requesting permission to access not only google.com but also bing.com and other search engines as permissions when installing extensions?

**Comment by iorate** [comment]
If I add new permissions, the extensions already installed will _stop working_ to require the users to grant the permissions. It will be annoying and unnecessary for most of the existing users.
