### ISSUE TITLE
Blacklists won't update due to browser cache

### ISSUE THREAD

**Issue by BitesizedLion** [iorate/ublacklist#267]
## Expected Behavior
Updating blacklist subscriptions via the "Options page" should update them.

## Actual Behavior
It fetches the same one due to cache
![image](https://user-images.githubusercontent.com/42980888/187447402-f6dab7d4-59c5-43b3-b4dd-1637b9b0fd44.png)

## Steps to Reproduce the Problem

1. Update a subscription
1. Change the subscription's content on your server
1. Update the subscription again

## Specifications

- OS: Windows 10
- Browser: Version 104.0.5112.102

## Other
Maybe there is a way for you to override the cache? Not sure how long cache lasts on the browser

**Comment by iorate** [comment]
Because I think that caching should be controlled between the browser and the server via HTTP headers, this extension calls `fetch` without cache options, and I have no plans to modify the behavior.

If you have control over the subscription server, you may want to update the cache settings.
If you host subscriptions on GitHub, files are cached for 5 minutes (ref: https://stackoverflow.com/questions/46551413/github-not-update-raw-after-commit).
