### ISSUE TITLE
This addon's permission are a bit scary

### ISSUE THREAD

**Issue by phaolo2** [iorate/uBlacklist#27]
This extension seems neat, but the fact that it requires "Access your data" (usernames and passwords potentially included) on 194 sites is quite scary (only 3 listed, by the way).

Is it possible to limit it to fewer sites and permissions, at least optionally?
(for example: only google.com and no usernames and passwords)

**Comment by chi-mira-81** [comment]
Access your data for www.google.com
Access your data for www.google.ad
Access your data for www.google.ae
Access your data on 190 other sites

Would you please list all 190 other sites, please ?
Or point out where in the source code we will find it ?

**Comment by iorate** [comment]
Google provides their service on many domains besides google.com, for example, `google.co.uk`, `google.co.jp`, `google.com.hk` and so on.
For users who use such domains, this extension requires permissions for ALL of them. Full list can be seen on the options page (only on Chromium-based browsers) or [the source code](https://github.com/iorate/uBlacklist/blob/master/src/manifest.json.js#L58).

If I remove some of the permissions, this extension will not work for some existing users. That breaking change is not acceptable to me, although not so many users will be involved.

"Access your data" cannot be reduced to a more limited permission, as long as this extension modifies search result pages.
As for passwords, I think this extension cannot access passwords, because passwords are entered on `accounts.google.*` while this extension requires permissions for `www.google.*` only.

**Comment by phaolo2** [comment]
Thank you for your reply.
That's more reassuring, even if I wish that Firefox improved their permissions options.
Btw, in the meantime I found an extension that shows them in more detail: Permission Inspector
