### ISSUE TITLE
Apple Store Review rejected

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/ublacklist#303]
![Screenshot 2022-12-17 at 11 17 14](https://user-images.githubusercontent.com/4635725/208221382-497c3be5-539a-44eb-86c3-cbb579b8bdd2.png)

Attachment:
![Screenshot 2022-12-16 at 1 20 56 PM](https://user-images.githubusercontent.com/4635725/208221406-9e4773cf-c7f1-4f3e-adc3-68b1dc7a3ee1.png)

I checked this issue and then found that actually Github has been filtered out, the feedback from the reviewer is that Google Ad related to Github is not filtered out (as shown in the attachment)

I would like to confirm if this is a bug, or if Google Ad is indeed not filtered out. Thank you.

**Comment by iorate** [comment]
Thank you for your report.

Intentionally I have not added code to filter ads for the following reasons:

1. it is controversial whether it is acceptable to hide ads, which are a source of revenue for search engines, so I think it should be done by each user with an ad/content blocker.
2. filtering by URL may be difficult because ads may not expose their actual URLs.

However, if the Apple Store does not accept this explanation, I will add code to filter ads.

**Comment by HoneyLuka** [comment]
Thanks for the explanation, I will tell this information to apple reviewer.

**Comment by HoneyLuka** [comment]
Apple accepted this clarification and the review has been approved.🎉

**Comment by iorate** [comment]
Thank you!
