### ISSUE TITLE
Would it be possible to exclude all websites that demands payment for their usage?

### ISSUE THREAD

**Issue by LarsBernstorff** [iorate/ublacklist#370]
I'm so fed up with the search results from google. Almost every search leads me to a site on which I need to pay to use. I wish for a setting in ublacklist, so that if someone added a particular website that requires payment, then I won't see it in my search results.

**Comment by corvec** [comment]
This seems out of scope for this project since it doesn't house the blocklists itself. The https://github.com/rjaus/awesome-ublacklist project seems like it would be a good fit, though.

I found the [Free Internet Plugin](https://freeinternetplugin.com/) Chrome extension that seems to do what you're looking for. I'm not sure why they didn't expose a subscription list that uBlacklist could use, though, but I've created a [Feature Request](https://github.com/hackernoon/Free-Internet-Plugin/issues/20) on their repo asking for it.

If they're not receptive, I think it would be pretty straightforward to build it yourself. I think you basically just need to convert their [site list](https://github.com/hackernoon/Free-Internet-Plugin/blob/main/src/js/background.js#L5) into a subscription file, which the README for this repo gives some instructions on how to do. If you do all that, I recommend submitting a PR to this repo and/or https://github.com/rjaus/awesome-ublacklist project to add a link to yours.

**Comment by iorate** [comment]
Closing this issue as @corvec 's answer is appropriate.
