### ISSUE TITLE
[off topic request] similar add-on for Bing search engine possible?

### ISSUE THREAD

**Issue by fortunewalla** [iorate/uBlacklist#45]
I am not a web developer but would it be possible to make a similar add-on for Bing search engine?

Thanks for the add-on. Very useful for filtering spam websites. 👏

**Comment by iorate** [comment]
> would it be possible to make a similar add-on for Bing search engine?

Yes.
This extension already has support for Startpage.com and DuckDuckGo (initial support), although it needs to be manually enabled in the options page.
YOU can add support for Bing referring to [README](https://github.com/iorate/uBlacklist#engine) and open a pull request.
Otherwise, you can also fork this repository and publish a version that is enabled on Bing by default.

**Comment by fortunewalla** [comment]
thanks
