### ISSUE TITLE
v.8.8.1 significantly impacts Safari performance

### ISSUE THREAD

**Issue by Bustycat** [iorate/ublacklist#492]
## Expected Behavior
- Smooth performance

## Actual Behavior
- Safari becomes very stuttering and could crash on iOS and iPadOS sometimes.
- My iPhone and iPad are both heated.

## Steps to Reproduce the Problem

1. Update uBlacklist to v.8.8.1 on iOS, iPadOS or macOS
2. Make sure uBlacklist enabled for Safari

## Specifications

- Browser: Safari v17.5
- Other extensions/add-ons: (unnecessary)

**Comment by frank-f** [comment]
For me on top of the stuttering, Safari crashes every time I close the last Tab or try to open a new one.

**Comment by Bustycat** [comment]
> I didn't test it in detail, but there are some problems with the performance. I tested it on mac, and when I opened the new tab (command + T), I would feel an obvious delay, and the problem disappeared after disabling uBlacklist.

The Settings app on iOS/iPadOS can be also stuttering when uBlacklist is enabled inside the Safari page.

**Comment by r-thomson** [comment]
I have an older iPhone and with this latest update it's enough to crash Safari consistently.

**Comment by Bustycat** [comment]
> I have an older iPhone and with this latest update it's enough to crash Safari consistently.

I tested with iPhone 15 Plus and iPad mini 6. They are a bit outdated actually.

**Comment by tsm55555** [comment]
> For me on top of the stuttering, Safari crashes every time I close the last Tab or try to open a new one.

Same here. Safari crashes every time I try to switch profiles or groups. Also, after I search for something on Google, I cannot click the search results, and my phone starts getting really hot. I'm using iPhone 15 Pro on iOS 17.5.1.

**Comment by iorate** [comment]
@HoneyLuka I appreciate your prompt action.

The problem occurs with my own build too. When Safari crashes, Xcode reports that "uBlacklist" was killed by OS because of too much memory, but not always. I guess some code introduced by #490 (my own code or dependencies) has a problem with Safari, but I have no idea what it is.
@HoneyLuka Do you have any thoughts?

If the problem cannot be solved immediately, we may need to create a branch for Safari based on v8.7.1 and cherry-pick bug fixes of the main branch.

**Comment by iorate** [comment]
I’ve observed that even after completely disabling the background page, the problem persists. On the other hand, it doesn’t occur when the content script is empty. However, identifying the specific code in the content script causing the problem remains unclear. It seems to me that gradually applying changes in #490 leads to a gradual increase in memory usage. Additionally, reducing the number of entries in the `content_scripts` field in `manifest.json` mitigates the problem.

I’ve also noticed that enabling the extension via ‘Always Allow on *Every* Website’ causes the settings page in Safari settings (not the extension’s options page) to become very slow and display incorrect permission information. To be specific, the dropdowns show ‘Ask’ even though they actually behave as ‘Allow’. After encountering this issue, every page—regardless of its relation to the extension—consumes a significant amount of memory. Escaping this state is challenging because Safari remembers the ‘Always Allow on *Every* Website’ setting, which cannot be reset by reinstalling the extension. I haven’t encountered this problem on my iPad, where the extension is enabled via ‘Always Allow on *This* Website’.
Interestingly, this phenomenon persists even with v8.8.2 (the same as v8.7.1) to some extent. With my iPhone, enabling ‘Always Allow on *Every* Website’ made the settings page slow, and every page exhibits high memory usage (thousands of bytes).

My hypothesis is that this issue is related to a memory leak bug of Safari concerning content script permissions (possibly related to issue #398 ?) and the memory usage increase in v8.8.0 has brought this bug to light.

@HoneyLuka, I apologize for interrupting your busy schedule, but could you please investigate whether 'Always Allow on *This* Website' does not trigger the bug and ‘Always Allow on Every Website’ does? Perhaps you need to build v8.8.1 with a different bundle ID to reset the permission settings.

**Comment by iorate** [comment]
@HoneyLuka Thank you for your rapid response!

> 1. Maybe every enabled matches will trigger the content-script, even this page was not loaded at all? (can we print some log in content-script file to verify this?)

As far as I tested, the content script is not loaded when search engine result pages (SERPs) are not loaded. I added code that modifies DOM, calls `console.log()`, and sends blocklists to the background page to the content script, but it had no effect unless SERPs are loaded.
Nonetheless, memory usage on non-SERP pages increases significantly.

> 2. If above is true, maybe some memory leak in content-script. We can find the issue by debugging the code in the content-script in depth.(disable functions one by one)
> 3. If a blank content-script file still can't solve the problem. This means that 1 and 2 are wrong

I'm not sure if 1. is true, but since the problem does not occur with an empty content script, I believe that the *content* of the content script is somehow affecting the bug. I will continue to look for code that increases memory usage.

> 4. Is it possible to avoid this issue by reducing matches list in manifest?

I think so, but how do we select which matches to remove...?

**Comment by iorate** [comment]
Perhaps simply replacing the content script with a short script that imports it might fix the problem...?

import-content-script.js
```javascript
import("./content-script.js");
```

@HoneyLuka Would you please try #505 , which is based on v8.8.1 and introduces `import-content-script.js`?

**Comment by iorate** [comment]
@HoneyLuka Thank you for testing the solution so quickly! I'll merge it soon.

**Comment by aug-dev** [comment]
>Perhaps simply replacing the content script with a short script that imports it might fix the problem...?

No way! 😅

I was regularly checking this issue, and to think that this would be the solution haha.

Software development can be so weird sometimes.

**Comment by Bustycat** [comment]
Is it just my Safari 18 that the performance becomes worse again?

**Comment by Bustycat** [comment]
> > Is it just my Safari 18 that the performance becomes worse again?
> 
> I checked it and it seems normal macOS 14.7.1 Safari 18.1

Seems that was simply caused by a not-found subscription.
