### ISSUE TITLE
Sync function not working in some language env

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/ublacklist#512]
## Actual Behavior

Both Google Drive and Dropbox is not working in ko env

![uBlacklist sync with Dropbox](https://github.com/user-attachments/assets/3058bde4-8e72-44e0-9ae1-2a2b04c337e8)
![uBlacklist sync with Dropbox - Error](https://github.com/user-attachments/assets/7b6c9586-4730-48be-8340-0f94998a3f45)

## Steps to Reproduce the Problem

as shown above, the key point is **the callback url is mismatch**

The correct url is `https://iorate.github.io/ublacklist/callback`
But in ko env, it change to `https://iorate.github.io/ublacklist/ko/callback`

I suggest user to change browser language to en, it solved the problem.

- Language: ko

**Comment by aug-dev** [comment]
Hey there.

After some investigation, I found that this issue is mainly being caused by two things:

- A problem with a `getWebsiteURL()` function that returns a localized version of the callback page that doesn't exist.
- The Korean page is not registered as a `redirect_uri` on the OAuth configurations for Dropbox and Google Drive. (This is probably true for other locales too.)

The second thing is something that only `iorate` can fix by adding the URLs to the respective App Consoles.

## Considerations about the second option

I think that adding a page that doesn't exist to the `redirect_uri`s is probably not a good idea, since it would *probably* be better to se the English version than a **Page Not Found 404** message.

Although, to be fair, the page is not even seen by the user if everything goes well, so it probably would matter that much.

## Code changes

The current version of the function returns a localized version of the callback page, but the problem is that it checks for the **extension's i18n files, not the website's**.

This is a problem because even though the extension itself has a Korean version, the documentation website doesn't.

https://github.com/iorate/ublacklist/blob/5a86624e252e0fbfb851d2bfc106841ad6e145ae/src/scripts/locales.ts#L19-L24

I added this extra condition, and after some basic testing, it seems that the issue is fixed (I tested only on Dropbox):

https://github.com/aug-dev/ublacklist-experiments/blob/ede7037d2152276e752a0e5172e5da6bb63ab57a/src/scripts/locales.ts#L19-L26

I haven't made a PR yet because the solution is still somewhat crude, since the localized values are hard-coded (which is not ideal).

I will try to come up with something better, but if @iorate beats me to it, I hope this can be of some help.

**Comment by iorate** [comment]
@HoneyLuka @aug-dev I appreciate your report and investigation.

I think the problem is located here:
https://github.com/iorate/ublacklist/blob/5a86624e252e0fbfb851d2bfc106841ad6e145ae/src/_locales/ko/messages.json.ts#L8

Since this entry is translated despite the lack of a Korean translation of the website, `translate("websiteLocale")` returns `"ko"` and `getWebsiteURL("callback")` returns `"https://iorate.github.io/ublacklist/ko/callback"`, which does not exist.
