### ISSUE TITLE
Add Baidu support 

### ISSUE THREAD

**Issue by auroraeffect** [iorate/uBlacklist#56]
I am really enjoying the extension, blocking some low-quality site is very useful for me.

For some reason, I need to use Baidu( most popular in Chinese searching ), but those low-quality sites show up again, can you add support for Baidu.

**Comment by tasy5kg** [comment]
I am agree with that. Over 70% Chinese people are using Baidu while only 2% are using Google.

**Comment by genment** [comment]
I used to try to add support for Baidu.com, but I finally failed to do so, because baidu.com is using its own redirect URL (`www.baidu.com/link?url=xxxxx`) for all search results. There is no way to obtain a website's real URL directly.

**Comment by iorate** [comment]
As @genment said, it is *technically impossible* for uBlacklist to work with Baidu because the Baidu SERP does not expose real URLs.

**Comment by pixiandouban** [comment]
Found a Tampermonkey script that can expose the real URLS. Don't know whether it's useful for you to apply it to Baidu.com.
[AC-baidu:重定向优化百度搜狗谷歌必应搜索_favicon_双列](https://greasyfork.org/zh-CN/scripts/14178)

**Comment by iorate** [comment]
@pixiandouban 
[AC-baidu](https://greasyfork.org/zh-CN/scripts/14178/code) seems to get real URLs by actually accessing `www.baidu.com/link?url=...` and resolving redirects using `GM_xmlhttpRequest`.
It is not impossible to take this approach in uBlacklist, but I don't like it because it increases the load on the users' devices and Baidu's servers.

[Google Hit Hider by Domain](https://greasyfork.org/en/scripts/1682) takes a different approach: it reads texts in search results as the below image. This approach does not always work, however, because the texts are sometimes not URLs, and sometimes truncated.
<img width="714" alt="ghhbd-baidu" src="https://user-images.githubusercontent.com/682043/103459285-91e00700-4d51-11eb-9145-5d841146f4f1.png">

These approaches work not perfectly, but to some extent. To be honest, I don't want to implement these - but PRs are always welcome.

**Comment by CPCer** [comment]
Hi developer @iorate , when I'm using [AC-Baidu](https://greasyfork.org/zh-CN/scripts/14178/code), it is giving right URLs on the page (after it shreds those redirect urls). 
I wonder if you might enable supporting for other search engines, and thus we can combine and customize uBlacklist and other anti-redirect extensions.

Thank you for your attention!🙇‍♂️🙇‍♂️

**Comment by MisteryMonster** [comment]
@iorate Seems like in regular web page search, URL can be query by div with `mu` attribute:
```
document.getElementById('content_left').querySelector("div [id='1']").getAttribute("mu")

```
when search result mix with video preview or others conditions, `mu` attribute will disapear, we can't get the full URL but we can get the domain name by it sub element `<span class="c-showurl">`. Ads also no `mu` attribute, but it can handle by other userscript like [Kill Baidu AD](https://greasyfork.org/en/scripts/24192-%E7%99%BE%E5%BA%A6%E5%B9%BF%E5%91%8A-%E9%A6%96%E5%B0%BE%E6%8E%A8%E5%B9%BF%E5%8F%8A%E5%8F%B3%E4%BE%A7%E5%B9%BF%E5%91%8A-%E6%B8%85%E7%90%86)
