### ISSUE TITLE
Add Onedrive Sync Support

### ISSUE THREAD

**Issue by yidasanqian** [iorate/uBlacklist#66]
att
## Specifications
  - Browser: edge

**Comment by iorate** [comment]
note: https://github.com/MicrosoftDocs/azure-docs/issues/62164

**Comment by iorate** [comment]
As described in the above issue, it is difficult to implement Microsoft OAuth in browser extensions (with good user experience).

When the app type is "web apps", the extension cannot get access tokens because "cross-origin token redemption is permitted only for the 'Single-Page Application' client-type". I guess the reason of this error is that extension origins are form of `chrome-extension://...` while redirect URLs returned by `identity.getRedirectURL` are form of `https://....chromiumapp.org/...`.

When the app type is "single-page application (SPA)", another problem occurs: refresh tokens live only for 24 hours. After 24 hours passed, the user has to log-in again, which is bad user experience. We can extend the refresh token's life by calling `identity.launchWebAuthFlow` in the background page, but if the user closes the browser and 24 hours passed, the refresh tokens will expire.

There might be a better way, but I don't know one for now.

**Comment by rxliuli** [comment]
I think you can refer to stylus/tampermonkey

**Comment by Rex501st** [comment]
I'm going to update this thread as I would like to see this.
