### ISSUE TITLE
Are you willing to develop a Safari version?

### ISSUE THREAD

**Issue by XIYO** [iorate/uBlacklist#67]
I used google Translate

I use it well on my window edge (chrome base).
This is a very good extension. You can get rid of the damn shit site. I am very happy.
However, I prefer native apps. I don't use chrome very often. I only use it very occasionally when it can't be helped. Because you are using the cloud.
So I would like to have a safari version too.

Thanks for reading.

**Comment by iorate** [comment]
> Are you willing to develop a Safari version?

Currently, no.

It seems possible to create a Safari port using the converter: [Converting a Web Extension for Safari](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari).
However, I have no motivation to do it because I don't use Safari and don't have a membership of Apple Developer Program, which is necessary to publish a Safari extension to App Store.

(I may change my mind later)

**Comment by ciryon** [comment]
Just tested to convert the extension for Safari and the conversion was easy enough and the Xcode project could build and install extension into Safari without problems. I could then, inside Safari, setup the extension blacklist. But, then unfortunately it did not work to actually filter out Google search results. Perhaps a permission problem. I have just given this 15 minutes of experimentation, but may look into it more in the future. If this works it's likely I can put it up on App Store as well later.

**Comment by iorate** [comment]
> But, then unfortunately it did not work to actually filter out Google search results. Perhaps a permission problem.

After I replaced `https://www.google.com/search?*` with `https://www.google.com/*` in manifest.json, it worked. Safari seems to ignore match patterns which paths are not `/*`.
<img width="422" alt="xcode" src="https://user-images.githubusercontent.com/682043/104738889-6dd8e880-5789-11eb-9da1-44f8a3f76a99.png">

**Comment by iorate** [comment]
@ciryon 
I created [a new branch](https://github.com/iorate/uBlacklist/tree/chrome-mv3-safari) to add support for Safari.
Would you please try it?
```shell
git clone https://github.com/iorate/uBlacklist.git -b chrome-mv3-safari
cd uBlacklist
yarn
yarn build:safari:development
xcrun safari-web-extension-converter dist/safari/development
```
Major changes:
- Remove "Other search engines" from the options page. Instead we can activate the extension by clicking the toolbar icon.
- Remove "Sync" from the options page. Sync cannot be (easily) implemented in Safari because `browser.identity` is not provided.

**Comment by ciryon** [comment]
Awesome! It works now! On first google search I had to give permission to the addon to read from google.com but that was it.
I have never published a Safari extension before (only iOS apps) but I could give it a go if you're ok with it.

**Comment by iorate** [comment]
@ciryon
Thank you for your feedback.
The branch is already merged into master and app icons are available in `/safari-icons`.

> I could give it a go if you're ok with it.

I appreciate your kindness, but I'd rather do it myself ([I've changed my mind](#issuecomment-753488933)).  Is it OK?

**Comment by ciryon** [comment]
Absolutely, it's even better if you publish it yourself! Looking forward to seeing the extension in the store! Thanks for the good work!

**Comment by ciryon** [comment]
Uh, someone beat you to it?

![Screenshot 2021-01-25 at 10 20 00](https://user-images.githubusercontent.com/151225/105685879-e3b22200-5ef6-11eb-915d-73f1773da44f.png)

**Comment by iorate** [comment]
The developer contacted me and I decided to leave the Safari port to him.
He already changed the price to free, and maybe will release the source code as open-source.

**Comment by iorate** [comment]
Close this for now
