### ISSUE TITLE
Add Qwant support

### ISSUE THREAD

**Issue by sherguin** [iorate/uBlacklist#82]
I have recently replaced Google.com with Qwant.com to search the Internet, and suddenly seriously miss uBlacklist again. How easy is it to make uBlacklist compatible with other search engines - I see it isn't easy with Baidu. Looking forward to hearing your thoughts.
Thanks, Sheridan

**Comment by iorate** [comment]
I have no motivation to add support for Qwant because it is not available in Japan, where I live.

However, you (or others) can always create pull requests. In most cases, it is not so difficult to add support for other search engines. (Baidu is an exception because it does not show real URLs. Ecosia is another exception because it uses Nuxt so modifying DOM leads to unintended behavior.)
